# Generated by Django 5.1.7 on 2026-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='interval_days',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de días entre ocurrencias (solo para recurrencia personalizada)'),
        ),
    ]
