# Generated by Django 5.1.7 on 2026-08-13 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0002_taskschedule_interval_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('task_status_changed', 'Task Status Changed'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('project_status_changed', 'Project Status Changed'), ('inbox_created', 'Inbox Created'), ('inbox_processed', 'Inbox Processed'), ('inbox_deleted', 'Inbox Deleted'), ('schedule_created', 'Schedule Created'), ('schedule_deleted', 'Schedule Deleted'), ('reminder_created', 'Reminder Created'), ('reminder_deleted', 'Reminder Deleted'), ('template_created', 'Template Created'), ('template_used', 'Template Used'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_deleted', 'Event Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Contexto adicional del evento', null=True)),
                ('summary', models.CharField(blank=True, help_text='Resumen corto para listados y feeds', max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type', 'timestamp'], name='events_syst_action__703f56_idx'), models.Index(fields=['user', 'timestamp'], name='events_syst_user_id_11bcb9_idx'), models.Index(fields=['content_type', 'object_id'], name='events_syst_content_a6ab33_idx')],
            },
        ),
    ]
