# Generated by Django 5.1.7 on 2026-08-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=60, help_text='Ancho en cm')),
                ('height', models.IntegerField(default=40, help_text='Alto en cm')),
                ('depth', models.IntegerField(default=40, help_text='Profundidad en cm')),
                ('color', models.CharField(default='#8B4513', help_text='Color en formato hex (#RRGGBB)', max_length=7)),
                ('material_type', models.CharField(choices=[('WOOD', 'Madera'), ('METAL', 'Metal'), ('PLASTIC', 'Plástico'), ('CARDBOARD', 'Cartón'), ('GLASS', 'Vidrio'), ('SPECIAL', 'Especial')], default='CARDBOARD', max_length=50)),
                ('is_open', models.BooleanField(default=False, help_text='Estado actual (abierto/cerrado)')),
                ('is_locked', models.BooleanField(default=False, help_text='Si está cerrado con llave')),
                ('required_key', models.CharField(blank=True, help_text='ID del objeto/llave necesario', max_length=100)),
                ('mass', models.DecimalField(decimal_places=2, default=1.0, help_text='Masa en kg', max_digits=10)),
                ('capacity', models.IntegerField(default=10, help_text='Capacidad de items')),
                ('contents', models.JSONField(default=list, help_text='Lista de items dentro de la caja')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='./box_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='rooms.room')),
            ],
        ),
    ]
