# Generated by Django 5.1.7 on 2026-08-10 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_add_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomobject',
            name='room',
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cell_type', models.CharField(choices=[('UNIVERSE', 'Universo'), ('ROOM', 'Habitación'), ('CONTAINER', 'Contenedor'), ('FURNITURE', 'Mobiliario'), ('OBJECT', 'Objeto'), ('ITEM', 'Item')], max_length=20)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(blank=True, help_text='Ancho en cm', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Alto en cm', null=True)),
                ('depth', models.IntegerField(blank=True, help_text='Profundidad en cm', null=True)),
                ('color', models.CharField(blank=True, help_text='Color hex #RRGGBB', max_length=7, null=True)),
                ('material_type', models.CharField(blank=True, choices=[('WOOD', 'Madera'), ('METAL', 'Metal'), ('PLASTIC', 'Plástico'), ('CARDBOARD', 'Cartón'), ('GLASS', 'Vidrio'), ('SPECIAL', 'Especial')], max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Capacidad de items', null=True)),
                ('contents', models.JSONField(blank=True, default=list, help_text='Items contenidos')),
                ('is_open', models.BooleanField(blank=True, help_text='Estado actual', null=True)),
                ('is_locked', models.BooleanField(blank=True, help_text='Si está cerrado con llave', null=True)),
                ('required_key', models.CharField(blank=True, help_text='ID del objeto/llave necesario', max_length=100)),
                ('mass', models.DecimalField(blank=True, decimal_places=2, help_text='Masa en kg', max_digits=10, null=True)),
                ('effect', models.JSONField(blank=True, help_text='Efecto/interacción de la celda', null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='./cell_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rooms.cell')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='rooms.room')),
            ],
            options={
                'ordering': ['cell_type', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Box',
        ),
        migrations.DeleteModel(
            name='RoomObject',
        ),
    ]
