# Generated by Django 5.1.7 on 2026-08-10 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_add_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='position_z',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_room',
            field=models.ForeignKey(blank=True, limit_choices_to={'cell_type': 'ROOM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.cell'),
        ),
    ]
