# Generated by Django 5.1.7 on 2026-08-10 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_add_player_position_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room'),
        ),
    ]
