# Generated by Django 5.1.7 on 2026-08-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_revert_playerprofile_current_room_to_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='position_z',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='color_primary',
            field=models.CharField(default='#2196f3', help_text='Color primario en formato hex (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='cell',
            name='color_secondary',
            field=models.CharField(default='#1976d2', help_text='Color secundario en formato hex (#RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='cell',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si la celda está activa'),
        ),
        migrations.AddField(
            model_name='cell',
            name='length',
            field=models.IntegerField(default=30, help_text='Largo en cm'),
        ),
        migrations.AddField(
            model_name='cell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_cells', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cell',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='Propiedades extendidas en JSON'),
        ),
        migrations.AddField(
            model_name='cell',
            name='health',
            field=models.IntegerField(default=100, help_text='Salud/durabilidad (0-100)'),
        ),
        migrations.AddField(
            model_name='cell',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=22.0, help_text='Temperatura en °C', max_digits=5),
        ),
        migrations.AddField(
            model_name='cell',
            name='lighting_intensity',
            field=models.IntegerField(default=50, help_text='Intensidad de iluminación (0-100)'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sound_ambient',
            field=models.CharField(blank=True, help_text='Sonido ambiente', max_length=100),
        ),
        migrations.AddField(
            model_name='cell',
            name='texture_url',
            field=models.URLField(blank=True, help_text='URL de la textura/imagen'),
        ),
        migrations.AddField(
            model_name='cell',
            name='pitch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='yaw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cell',
            name='density',
            field=models.DecimalField(decimal_places=2, default=2.4, help_text='Densidad en g/cm³', max_digits=5),
        ),
        migrations.AddField(
            model_name='cell',
            name='friction',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Coeficiente de fricción', max_digits=3),
        ),
        migrations.AddField(
            model_name='cell',
            name='restitution',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Coeficiente de restitución (rebote)', max_digits=3),
        ),
        migrations.AddField(
            model_name='cell',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Opacidad (0.0-1.0)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(choices=[('UNIVERSE', 'Universo'), ('ROOM', 'Habitación'), ('AREA', 'Área'), ('CONTAINER', 'Contenedor'), ('FURNITURE', 'Mobiliario'), ('OBJECT', 'Objeto'), ('ITEM', 'Item'), ('PORTAL', 'Portal'), ('DOOR', 'Puerta'), ('DECORATION', 'Decoración')], max_length=20),
        ),
    ]
