# Generated by Django 5.1.7 on 2026-08-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_add_missing_fields_to_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidirectional', models.BooleanField(default=True)),
                ('energy_cost', models.IntegerField(default=0)),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_connections', to='rooms.cell')),
                ('from_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='rooms.cell')),
                ('to_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='rooms.cell')),
            ],
            options={
                'verbose_name': 'Conexión entre celdas',
                'verbose_name_plural': 'Conexiones entre celdas',
                'unique_together': {('from_cell', 'to_cell', 'entrance')},
            },
        ),
    ]
