# Generated by Django 5.1.7 on 2026-08-10

from django.db import migrations


def migrate_rooms_to_cells(apps, schema_editor):
    """
    Migra datos de Room a Cell, EntranceExit a Cells tipo DOOR,
    Portal a Cells tipo PORTAL, y actualiza todas las referencias.
    Ahora deja que PostgreSQL asigne IDs nuevos y mapea room.id -> cell.id.
    """
    Room = apps.get_model('rooms', 'Room')
    Cell = apps.get_model('rooms', 'Cell')
    PlayerProfile = apps.get_model('rooms', 'PlayerProfile')
    RoomConnection = apps.get_model('rooms', 'RoomConnection')
    EntranceExit = apps.get_model('rooms', 'EntranceExit')
    Portal = apps.get_model('rooms', 'Portal')
    Message = apps.get_model('rooms', 'Message')
    Comment = apps.get_model('rooms', 'Comment')
    Evaluation = apps.get_model('rooms', 'Evaluation')
    RoomMember = apps.get_model('rooms', 'RoomMember')
    RoomNotification = apps.get_model('rooms', 'RoomNotification')
    Notification = apps.get_model('rooms', 'Notification')

    # 1. Migrar Rooms a Cells tipo ROOM sin fijar ID
    room_to_cell = {}
    for room in Room.objects.all():
        cell = Cell(
            name=room.name,
            cell_type='ROOM',
            position_x=room.x,
            position_y=room.y,
            position_z=room.z,
            width=room.width,
            height=room.height,
            length=room.length,
            color=room.color_primary,
            color_primary=room.color_primary,
            color_secondary=room.color_secondary,
            material_type=room.material_type,
            description=room.description,
            is_active=room.is_active,
            properties=room.special_properties or {},
            owner=room.owner,
            created_at=room.created_at,
            updated_at=room.updated_at,
            pitch=getattr(room, 'pitch', 0),
            yaw=getattr(room, 'yaw', 0),
            roll=getattr(room, 'roll', 0),
            mass=room.mass,
            density=room.density,
            friction=room.friction,
            restitution=room.restitution,
            health=room.health,
            temperature=room.temperature,
            lighting_intensity=room.lighting_intensity,
            sound_ambient=room.sound_ambient,
            texture_url=room.texture_url,
            opacity=room.opacity,
        )
        cell.save()
        room_to_cell[room.id] = cell

    # 2. Migrar EntranceExits a Cells tipo DOOR
    entrance_to_cell = {}
    for entrance in EntranceExit.objects.all():
        parent_cell = room_to_cell.get(entrance.room_id)
        door_cell = Cell(
            name=entrance.name,
            cell_type='DOOR',
            position_x=entrance.position_x or 0,
            position_y=entrance.position_y or 0,
            position_z=0,
            description=entrance.description or '',
            is_open=entrance.is_open,
            is_locked=entrance.is_locked,
            required_key=entrance.required_key,
            properties={
                'original_entrance_id': entrance.id,
                'face': entrance.face,
                'door_type': entrance.door_type,
                'material': entrance.material,
                'width': entrance.width,
                'height': entrance.height,
                'enabled': entrance.enabled,
            },
            created_at=getattr(entrance, 'created_at', None),
            updated_at=getattr(entrance, 'updated_at', None),
        )
        if parent_cell:
            door_cell.parent = parent_cell
        door_cell.save()
        entrance_to_cell[entrance.id] = door_cell

    # 3. Migrar Portales a Cells tipo PORTAL
    portal_to_cell = {}
    for portal in Portal.objects.all():
        entrance_cell = entrance_to_cell.get(portal.entrance_id)
        exit_cell = entrance_to_cell.get(portal.exit_id)
        portal_cell = Cell(
            name=portal.name,
            cell_type='PORTAL',
            position_x=0,
            position_y=0,
            position_z=0,
            description=f'Portal: {portal.entrance.room.name if portal.entrance else ""} -> {portal.exit.room.name if portal.exit else ""}',
            properties={
                'original_portal_id': portal.id,
                'energy_cost': portal.energy_cost,
                'cooldown': portal.cooldown,
                'entrance_cell_id': entrance_cell.id if entrance_cell else None,
                'exit_cell_id': exit_cell.id if exit_cell else None,
            },
            created_at=getattr(portal, 'created_at', None) or (getattr(portal.entrance, 'created_at', None) if portal.entrance else None),
            updated_at=getattr(portal, 'updated_at', None) or (getattr(portal.entrance, 'updated_at', None) if portal.entrance else None),
        )
        if entrance_cell and entrance_cell.parent:
            portal_cell.parent = entrance_cell.parent
        portal_cell.save()
        portal_to_cell[portal.id] = portal_cell

    # 4. Migrar RoomConnections a CellConnections
    CellConnection = apps.get_model('rooms', 'CellConnection')
    for rc in RoomConnection.objects.all():
        from_cell = room_to_cell.get(rc.from_room_id)
        to_cell = room_to_cell.get(rc.to_room_id)
        entrance_cell = entrance_to_cell.get(rc.entrance_id)
        if from_cell and to_cell:
            cc = CellConnection(
                from_cell=from_cell,
                to_cell=to_cell,
                entrance=entrance_cell,
                bidirectional=rc.bidirectional,
                energy_cost=rc.energy_cost,
            )
            cc.save()

    # 5. Actualizar PlayerProfile.current_room se pospone a 0010,
    # porque en este punto la FK todavía apunta a rooms_room.

    # 6. Actualizar Cells hijas usando parent en lugar de room
    for old_cell in Cell.objects.filter(room_id__isnull=False):
        new_parent = room_to_cell.get(old_cell.room_id)
        if new_parent:
            old_cell.parent = new_parent
            old_cell.save()

    # 7. Migrar Messages, Comments, Evaluations, RoomMembers, RoomNotifications, Notifications
    for msg in Message.objects.all():
        if msg.room_id in room_to_cell:
            msg.room = room_to_cell[msg.room_id]
            msg.save()

    for comment in Comment.objects.all():
        if comment.room_id in room_to_cell:
            comment.room = room_to_cell[comment.room_id]
            comment.save()

    for evaluation in Evaluation.objects.all():
        if evaluation.room_id in room_to_cell:
            evaluation.room = room_to_cell[evaluation.room_id]
            evaluation.save()

    for member in RoomMember.objects.all():
        if member.room_id in room_to_cell:
            member.room = room_to_cell[member.room_id]
            member.save()

    for rn in RoomNotification.objects.all():
        if rn.room_id in room_to_cell:
            rn.room = room_to_cell[rn.room_id]
            rn.save()

    for notif in Notification.objects.filter(related_room_id__isnull=False):
        if notif.related_room_id in room_to_cell:
            notif.related_room = room_to_cell[notif.related_room_id]
            notif.save()


def reverse_migrate_cells_to_rooms(apps, schema_editor):
    """
    Revierte la migración: convierte Cells de vuelta a Rooms y entidades originales.
    """
    Cell = apps.get_model('rooms', 'Cell')
    Room = apps.get_model('rooms', 'Room')
    PlayerProfile = apps.get_model('rooms', 'PlayerProfile')
    RoomConnection = apps.get_model('rooms', 'RoomConnection')
    EntranceExit = apps.get_model('rooms', 'EntranceExit')
    Portal = apps.get_model('rooms', 'Portal')
    Message = apps.get_model('rooms', 'Message')
    Comment = apps.get_model('rooms', 'Comment')
    Evaluation = apps.get_model('rooms', 'Evaluation')
    RoomMember = apps.get_model('rooms', 'RoomMember')
    RoomNotification = apps.get_model('rooms', 'RoomNotification')
    Notification = apps.get_model('rooms', 'Notification')

    cell_to_room = {}
    for cell in Cell.objects.filter(cell_type='ROOM'):
        room = Room(
            name=cell.name,
            description=cell.description,
            owner=cell.owner,
            x=cell.position_x,
            y=cell.position_y,
            z=cell.position_z,
            length=cell.length,
            width=cell.width,
            height=cell.height,
            color_primary=cell.color_primary or cell.color,
            color_secondary=cell.color_secondary,
            material_type=cell.material_type,
            is_active=cell.is_active,
            special_properties=cell.properties or {},
            created_at=cell.created_at,
            updated_at=cell.updated_at,
            pitch=getattr(cell, 'pitch', 0),
            yaw=getattr(cell, 'yaw', 0),
            roll=getattr(cell, 'roll', 0),
            mass=cell.mass,
            density=cell.density,
            friction=cell.friction,
            restitution=cell.restitution,
            health=cell.health,
            temperature=cell.temperature,
            lighting_intensity=cell.lighting_intensity,
            sound_ambient=cell.sound_ambient,
            texture_url=cell.texture_url,
            opacity=cell.opacity,
        )
        room.save()
        cell_to_room[cell.id] = room

    cell_to_entrance = {}
    for cell in Cell.objects.filter(cell_type='DOOR'):
        props = cell.properties or {}
        entrance = EntranceExit(
            name=cell.name,
            room=cell_to_room.get(cell.parent_id) if cell.parent_id else None,
            description=cell.description,
            face=props.get('face', 'NORTH'),
            position_x=cell.position_x,
            position_y=cell.position_y,
            enabled=props.get('enabled', True),
            is_open=cell.is_open,
            is_locked=cell.is_locked,
            required_key=cell.required_key,
            width=props.get('width', 100),
            height=props.get('height', 200),
            door_type=props.get('door_type', 'SINGLE'),
            material=props.get('material', 'WOOD'),
        )
        entrance.save()
        cell_to_entrance[cell.id] = entrance

    for cell in Cell.objects.filter(cell_type='PORTAL'):
        props = cell.properties or {}
        entrance_cell_id = props.get('entrance_cell_id')
        exit_cell_id = props.get('exit_cell_id')
        if entrance_cell_id and exit_cell_id:
            entrance = cell_to_entrance.get(entrance_cell_id)
            exit_entrance = cell_to_entrance.get(exit_cell_id)
            if entrance and exit_entrance:
                portal = Portal(
                    name=cell.name,
                    entrance=entrance,
                    exit=exit_entrance,
                    energy_cost=props.get('energy_cost', 10),
                    cooldown=props.get('cooldown', 300),
                )
                portal.save()

    CellConnection = apps.get_model('rooms', 'CellConnection')
    for cc in CellConnection.objects.all():
        from_room = cell_to_room.get(cc.from_cell_id)
        to_room = cell_to_room.get(cc.to_cell_id)
        entrance = cell_to_entrance.get(cc.entrance_id) if cc.entrance_id else None
        if from_room and to_room:
            rc = RoomConnection(
                from_room=from_room,
                to_room=to_room,
                entrance=entrance,
                bidirectional=cc.bidirectional,
                energy_cost=cc.energy_cost,
            )
            rc.save()

    for pp in PlayerProfile.objects.all():
        if pp.current_room_id in cell_to_room:
            pp.current_room = cell_to_room[pp.current_room_id]
            pp.save()

    for cell in Cell.objects.filter(parent_id__isnull=False):
        if cell.parent_id in cell_to_room:
            cell.parent = None
            cell.save()

    for msg in Message.objects.all():
        if msg.room_id in cell_to_room:
            msg.room = cell_to_room[msg.room_id]
            msg.save()

    for comment in Comment.objects.all():
        if comment.room_id in cell_to_room:
            comment.room = cell_to_room[comment.room_id]
            comment.save()

    for evaluation in Evaluation.objects.all():
        if evaluation.room_id in cell_to_room:
            evaluation.room = cell_to_room[evaluation.room_id]
            evaluation.save()

    for member in RoomMember.objects.all():
        if member.room_id in cell_to_room:
            member.room = cell_to_room[member.room_id]
            member.save()

    for rn in RoomNotification.objects.all():
        if rn.room_id in cell_to_room:
            rn.room = cell_to_room[rn.room_id]
            rn.save()

    for notif in Notification.objects.filter(related_room_id__isnull=False):
        if notif.related_room_id in cell_to_room:
            notif.related_room = cell_to_room[notif.related_room_id]
            notif.save()

    CellConnection.objects.all().delete()
    Cell.objects.filter(cell_type__in=['ROOM', 'DOOR', 'PORTAL']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_create_cell_connection'),
    ]

    operations = [
        migrations.RunPython(migrate_rooms_to_cells, reverse_migrate_cells_to_rooms),
    ]
