# Generated by Django 5.1.7 on 2026-08-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_migrate_rooms_to_cells'),
    ]

    operations = [
        # 1. Cambiar FKs de Room a Cell en modelos que sobreviven
        migrations.AlterField(
            model_name='playerprofile',
            name='current_room',
            field=models.ForeignKey(blank=True, limit_choices_to={'cell_type': 'ROOM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.cell'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.cell'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.cell'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.cell'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.cell'),
        ),
        # 2. Eliminar campo room de Cell (la jerarquía queda en parent)
        migrations.RemoveField(
            model_name='cell',
            name='room',
        ),
        # 3. Eliminar modelos intermedios y auxiliares que dependen de Room
        migrations.DeleteModel(
            name='RoomNotification',
        ),
        migrations.DeleteModel(
            name='RoomMember',
        ),
        migrations.DeleteModel(
            name='RoomConnection',
        ),
        migrations.DeleteModel(
            name='EntranceExit',
        ),
        migrations.DeleteModel(
            name='Portal',
        ),
        # 4. Finalmente eliminar Room
        migrations.DeleteModel(
            name='Room',
        ),
    ]
