# Generated by Django 5.2.3 on 2026-08-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_remove_room_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellconnection',
            options={},
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='navigation_history',
            field=models.JSONField(default=list, help_text='Historial de celdas visitadas para navegación con botón atrás'),
        ),
    ]
