# Generated by Django 5.1.7 on 2026-08-11 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_cellconnection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CellMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rooms.cell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cell', 'role'],
                'unique_together': {('cell', 'user')},
            },
        ),
    ]
