# Generated by Django 5.1.7 on 2026-08-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_add_cell_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_type',
            field=models.CharField(choices=[('UNIVERSE', 'Universo'), ('WORLD', 'Mundo'), ('ROOM', 'Habitación'), ('AREA', 'Área'), ('CONTAINER', 'Contenedor'), ('FURNITURE', 'Mobiliario'), ('OBJECT', 'Objeto'), ('ITEM', 'Item'), ('PORTAL', 'Portal'), ('DOOR', 'Puerta'), ('DECORATION', 'Decoración')], max_length=20),
        ),
    ]
