# Generated by Django 5.1.7 on 2026-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_add_world_cell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='geometry',
            field=models.JSONField(blank=True, help_text='GeoJSON/WKT del polígono/volumen de la celda para operaciones espaciales con Shapely', null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='position_geometry',
            field=models.JSONField(blank=True, help_text='GeoJSON/WKT representando la posición espacial exacta del jugador', null=True),
        ),
    ]
