# Generated by Django 5.1.7 on 2026-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del artículo (máx. 200 caracteres)', max_length=200, verbose_name='Título')),
                ('content', models.TextField(help_text='Contenido completo del artículo', verbose_name='Contenido')),
                ('excerpt', models.CharField(blank=True, default='', help_text='Breve descripción (máx. 300 caracteres)', max_length=300, verbose_name='Extracto')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('is_published', models.BooleanField(default=True, help_text='¿Está visible para los usuarios?', verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-publication_date'],
            },
        ),
    ]
