# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Slug para URLs', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: bi-question-circle)', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hex (#RRGGBB)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, help_text='Si la categoría está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Ayuda',
                'verbose_name_plural': 'Categorías de Ayuda',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickStartGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la guía', max_length=200)),
                ('slug', models.SlugField(help_text='Slug para URLs', unique=True)),
                ('description', models.TextField(help_text='Descripción breve')),
                ('content', models.TextField(help_text='Contenido de la guía en formato HTML/Markdown')),
                ('estimated_time', models.PositiveIntegerField(default=5, help_text='Tiempo estimado en minutos')),
                ('target_audience', models.CharField(choices=[('new_users', 'Nuevos usuarios'), ('intermediate', 'Usuarios intermedios'), ('power_users', 'Usuarios avanzados'), ('administrators', 'Administradores')], default='new_users', max_length=100)),
                ('prerequisites', models.TextField(blank=True, help_text='Prerrequisitos para completar la guía')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden en la secuencia de guías')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('completion_count', models.PositiveIntegerField(default=0, help_text='Número de veces completada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guía de Inicio Rápido',
                'verbose_name_plural': 'Guías de Inicio Rápido',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del artículo', max_length=200)),
                ('slug', models.SlugField(help_text='Slug para URLs', unique=True)),
                ('content', models.TextField(blank=True, help_text='Contenido del artículo en formato HTML/Markdown')),
                ('excerpt', models.TextField(blank=True, help_text='Resumen breve del artículo')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', help_text='Nivel de dificultad', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Si el artículo está publicado')),
                ('is_featured', models.BooleanField(default=False, help_text='Si es un artículo destacado')),
                ('requires_auth', models.BooleanField(default=False, help_text='Si requiere autenticación para ver')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Número de visualizaciones')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text="Número de votos 'útil'")),
                ('not_helpful_count', models.PositiveIntegerField(default=0, help_text="Número de votos 'no útil'")),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Descripción para SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Fecha de publicación', null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to=settings.AUTH_USER_MODEL)),
                ('referenced_content_block', models.ForeignKey(blank=True, help_text='Bloque de contenido relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='courses.contentblock')),
                ('referenced_course', models.ForeignKey(blank=True, help_text='Curso relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='courses.course')),
                ('referenced_lesson', models.ForeignKey(blank=True, help_text='Lección relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_articles', to='courses.lesson')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpcategory')),
            ],
            options={
                'verbose_name': 'Artículo de Ayuda',
                'verbose_name_plural': 'Artículos de Ayuda',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Pregunta', max_length=300)),
                ('answer', models.TextField(help_text='Respuesta en formato HTML')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, help_text='Si la FAQ está activa')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Número de visualizaciones')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text="Número de votos 'útil'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='help.helpcategory')),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HelpFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('was_helpful', models.BooleanField(help_text='Si el artículo fue útil')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Calificación del artículo')),
                ('comment', models.TextField(blank=True, help_text='Comentario adicional')),
                ('improvement_suggestions', models.TextField(blank=True, help_text='Sugerencias de mejora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='help.helparticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback de Ayuda',
                'verbose_name_plural': 'Feedback de Ayuda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Término de búsqueda', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Número de resultados encontrados')),
                ('has_results', models.BooleanField(default=False, help_text='Si encontró resultados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Búsqueda',
                'verbose_name_plural': 'Registros de Búsqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del tutorial', max_length=200)),
                ('slug', models.SlugField(help_text='Slug para URLs', unique=True)),
                ('description', models.TextField(help_text='Descripción del tutorial')),
                ('video_url', models.URLField(blank=True, help_text='URL del video (YouTube, Vimeo, etc.)')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL de la miniatura')),
                ('duration', models.DurationField(blank=True, help_text='Duración del video', null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tutorials', to='help.helpcategory')),
                ('referenced_lesson', models.ForeignKey(blank=True, help_text='Lección con video relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_tutorials', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Tutorial en Video',
                'verbose_name_plural': 'Tutoriales en Video',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
