# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la configuración', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Configuración activa actualmente')),
                ('model_name', models.CharField(default='llama2', help_text='Nombre del modelo de IA', max_length=100)),
                ('temperature', models.FloatField(default=0.7, help_text='Temperatura para la generación (0.0-2.0)')),
                ('max_tokens', models.IntegerField(default=2048, help_text='Máximo número de tokens en respuesta')),
                ('top_p', models.FloatField(default=0.9, help_text='Top-p sampling')),
                ('top_k', models.IntegerField(default=40, help_text='Top-k sampling')),
                ('system_prompt', models.TextField(default='Eres un asistente de IA útil y amigable.', help_text='Prompt del sistema que define el comportamiento del asistente')),
                ('initial_context', models.TextField(blank=True, help_text='Contexto inicial adicional para todas las conversaciones')),
                ('additional_data', models.JSONField(default=dict, help_text='Datos adicionales como objetos, archivos, texto, etc.')),
                ('enabled_functions', models.JSONField(default=list, help_text='Lista de funciones habilitadas para este asistente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Asistente',
                'verbose_name_plural': 'Configuraciones del Asistente',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(help_text='Comando original del usuario')),
                ('function_name', models.CharField(help_text='Nombre de la función ejecutada', max_length=100)),
                ('params', models.JSONField(default=dict, help_text='Parámetros pasados a la función')),
                ('result', models.JSONField(blank=True, help_text='Resultado de la ejecución', null=True)),
                ('success', models.BooleanField(default=False, help_text='Si la ejecución fue exitosa')),
                ('execution_time', models.FloatField(default=0.0, help_text='Tiempo de ejecución en segundos')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Comando',
                'verbose_name_plural': 'Registros de Comandos',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(help_text='ID único de la conversación', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Título auto-generado de la conversación', max_length=200)),
                ('messages', models.JSONField(default=list, help_text='Lista completa de mensajes de la conversación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si la conversación está activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.cell')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Presence',
                'verbose_name_plural': 'User Presences',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
