# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('calidad', 'Calidad'), ('rrhh', 'RRHH'), ('operaciones', 'Operaciones'), ('finanzas', 'Finanzas'), ('marketing', 'Marketing'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('schema', models.JSONField(default=list, verbose_name='Schema')),
                ('row_count', models.IntegerField(default=0, verbose_name='Registros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_bases', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Base de datos analista',
                'verbose_name_plural': 'Bases de datos analista',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('layout', models.JSONField(default=list, verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI / Indicador'), ('table', 'Tabla'), ('bar_chart', 'Gráfico de barras'), ('line_chart', 'Gráfico de líneas'), ('pie_chart', 'Gráfico de pastel'), ('text', 'Texto / Nota')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('source', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analyst.dashboard')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ETLSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_path', models.CharField(blank=True, max_length=200)),
                ('events_model', models.CharField(blank=True, choices=[('inbox', 'GTD Inbox (InboxItem)'), ('tasks', 'Tareas (Task)'), ('projects', 'Proyectos (Project)'), ('events', 'Agenda (Event)')], default='', max_length=20, verbose_name='Modelo Events')),
                ('fields', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('date_field', models.CharField(blank=True, max_length=100)),
                ('aggregations', models.JSONField(default=dict)),
                ('sql_override', models.TextField(blank=True)),
                ('chunk_size', models.PositiveIntegerField(default=5000)),
                ('max_rows', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_sources', to='analyst.analystbase', verbose_name='Base de datos analista')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_sources', to=settings.AUTH_USER_MODEL)),
                ('sim_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_sources', to='sim.simaccount', verbose_name='Cuenta Sim')),
            ],
            options={
                'verbose_name': 'Fuente ETL',
                'verbose_name_plural': 'Fuentes ETL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('steps', models.JSONField(default=list, verbose_name='Pasos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('function_key', models.CharField(max_length=100)),
                ('sources', models.JSONField(default=list)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Generando'), ('done', 'Listo'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('result_data', models.JSONField(default=list)),
                ('result_meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoredDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cache_key', models.CharField(max_length=120, unique=True)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('col_count', models.PositiveIntegerField(default=0)),
                ('columns', models.JSONField(default=list)),
                ('dtype_map', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('data_blob', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset Guardado',
                'verbose_name_plural': 'Datasets Guardados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'Inactivo'), ('running', 'Ejecutando'), ('done', 'Completado'), ('error', 'Error')], default='idle', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('steps_completed', models.PositiveIntegerField(default=0)),
                ('duration_s', models.FloatField(default=0.0)),
                ('runtime_params', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analyst.pipeline')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
                ('input_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs_as_input', to='analyst.storeddataset', verbose_name='Dataset entrada')),
                ('result_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs_as_result', to='analyst.storeddataset', verbose_name='Dataset resultado')),
            ],
            options={
                'verbose_name': 'Ejecucion de pipeline',
                'verbose_name_plural': 'Ejecuciones de pipeline',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='analyst.storeddataset', verbose_name='Dataset origen'),
        ),
        migrations.CreateModel(
            name='ETLJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('runtime_params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('idle', 'Inactivo'), ('running', 'Ejecutando'), ('done', 'Completado'), ('error', 'Error')], default='idle', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('rows_extracted', models.PositiveIntegerField(default=0)),
                ('duration_s', models.FloatField(default=0.0, help_text='Segundos de ejecución')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etl_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='analyst.etlsource')),
                ('result_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_jobs', to='analyst.storeddataset')),
            ],
            options={
                'verbose_name': 'Trabajo ETL',
                'verbose_name_plural': 'Trabajos ETL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('config', models.JSONField(verbose_name='Configuración del cruce')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_sources', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_sources', to='analyst.storeddataset', verbose_name='Último resultado')),
            ],
            options={
                'verbose_name': 'Cruce de datos',
                'verbose_name_plural': 'Cruces de datos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='analystbase',
            name='dataset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_base', to='analyst.storeddataset', verbose_name='Dataset'),
        ),
    ]
