# Generated by Django 5.1.7 on 2026-07-25 12:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0002_alter_mementoconfig_death_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mementoconfig',
            name='death_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2026, 7, 25))]),
        ),
    ]
