# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del bloque', max_length=200)),
                ('slug', models.SlugField(help_text='Identificador único para el bloque', unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del propósito del bloque')),
                ('content_type', models.CharField(choices=[('html', 'HTML Personalizado'), ('bootstrap', 'Componente Bootstrap'), ('markdown', 'Markdown'), ('json', 'JSON Estructurado'), ('text', 'Texto Simple'), ('image', 'Imagen'), ('video', 'Video'), ('quote', 'Cita'), ('code', 'Código'), ('list', 'Lista'), ('table', 'Tabla'), ('card', 'Tarjeta'), ('alert', 'Alerta'), ('button', 'Botón'), ('form', 'Formulario'), ('divider', 'Separador'), ('icon', 'Ícono'), ('progress', 'Barra de Progreso'), ('badge', 'Insignia'), ('timeline', 'Línea de Tiempo')], default='html', help_text='Tipo de contenido del bloque', max_length=20)),
                ('html_content', models.TextField(blank=True, help_text='Contenido HTML/Bootstrap')),
                ('json_content', models.JSONField(blank=True, default=dict, help_text='Contenido estructurado en JSON')),
                ('markdown_content', models.TextField(blank=True, help_text='Contenido en formato Markdown')),
                ('category', models.CharField(blank=True, help_text='Categoría del bloque', max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=500)),
                ('is_public', models.BooleanField(default=True, help_text='Bloque disponible para todos los tutores')),
                ('is_featured', models.BooleanField(default=False, help_text='Bloque destacado')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Cuántas veces se ha usado este bloque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloque de Contenido',
                'verbose_name_plural': 'Bloques de Contenido',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_hours', models.PositiveIntegerField(help_text='Duración total en horas')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tutor', models.ForeignKey(limit_choices_to={'cv__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('dropped', 'Abandonado')], default='active', max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Slug único para lecciones independientes')),
                ('description', models.TextField(blank=True, help_text='Descripción de la lección independiente')),
                ('is_published', models.BooleanField(default=False, help_text='¿Está publicada la lección independiente?')),
                ('is_featured', models.BooleanField(default=False, help_text='¿Es una lección destacada?')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('video', 'Video'), ('text', 'Texto'), ('quiz', 'Quiz'), ('assignment', 'Tarea')], default='video', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('quiz_questions', models.JSONField(blank=True, default=list)),
                ('assignment_instructions', models.TextField(blank=True)),
                ('assignment_file', models.FileField(blank=True, null=True, upload_to='courses/assignments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])])),
                ('assignment_due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Autor de la lección independiente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standalone_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del archivo', max_length=200)),
                ('file', models.FileField(upload_to='courses/lesson_attachments/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'mov', 'mp3', 'wav'])])),
                ('file_type', models.CharField(blank=True, help_text='Tipo de archivo detectado automáticamente', max_length=50)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto de Lección',
                'verbose_name_plural': 'Archivos Adjuntos de Lección',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('retries_left', models.PositiveIntegerField(default=3)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
            ],
            options={
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
