# Generated by Django 5.1.7 on 2026-07-20 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bibliografia',
            field=models.TextField(blank=True, help_text='Bibliografía básica'),
        ),
        migrations.AddField(
            model_name='course',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código UPN', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='competencia_general',
            field=models.TextField(blank=True, help_text='Competencia general'),
        ),
        migrations.AddField(
            model_name='course',
            name='componentes',
            field=models.TextField(blank=True, help_text='Componentes transversales'),
        ),
        migrations.AddField(
            model_name='course',
            name='creditos',
            field=models.PositiveIntegerField(blank=True, help_text='Créditos', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hl',
            field=models.PositiveIntegerField(blank=True, help_text='Horas de laboratorio', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hp',
            field=models.PositiveIntegerField(blank=True, help_text='Horas prácticas', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='ht',
            field=models.PositiveIntegerField(blank=True, help_text='Horas teóricas', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='logro_curso',
            field=models.TextField(blank=True, help_text='Logro del curso'),
        ),
        migrations.AddField(
            model_name='course',
            name='naturaleza',
            field=models.CharField(blank=True, help_text='Naturaleza: teórico, teórico-práctico, práctico', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='pc',
            field=models.PositiveIntegerField(blank=True, help_text='Práctica de campo', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requisitos',
            field=models.CharField(blank=True, help_text='Requisitos', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='sistema_evaluacion',
            field=models.TextField(blank=True, help_text='Sistema de evaluación'),
        ),
        migrations.AddField(
            model_name='course',
            name='sumilla',
            field=models.TextField(blank=True, help_text='Sumilla del curso'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='actividades',
            field=models.TextField(blank=True, help_text='Actividades'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='logro_semana',
            field=models.TextField(blank=True, help_text='Logro de la semana'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='saberes_esenciales',
            field=models.TextField(blank=True, help_text='Saberes esenciales'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='trabajo_campo',
            field=models.TextField(blank=True, help_text='Trabajo de campo / PC'),
        ),
        migrations.AddField(
            model_name='module',
            name='logro_unidad',
            field=models.TextField(blank=True, help_text='Logro de la unidad'),
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(help_text='Autor o autores', max_length=200)),
                ('titulo', models.CharField(help_text='Título del libro o artículo', max_length=300)),
                ('anio', models.CharField(blank=True, help_text='Año de publicación', max_length=10)),
                ('enlace', models.URLField(blank=True, help_text='Enlace o referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografia_items', to='courses.course')),
            ],
            options={
                'ordering': ['autor'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la evaluación: T1, T2, T3, T4, Final, Sustitutoria', max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en porcentaje', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('semana', models.PositiveIntegerField(help_text='Semana en la que se aplica')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la evaluación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='courses.course')),
            ],
            options={
                'ordering': ['semana'],
                'unique_together': {('course', 'nombre')},
            },
        ),
    ]
