# Generated by Django 5.1.7 on 2026-07-26 23:xx

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_upn_metodologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz_feedback_correct',
            field=models.CharField(blank=True, help_text='Retroalimentación general si acierta', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz_feedback_incorrect',
            field=models.CharField(blank=True, help_text='Retroalimentación general si falla', max_length=500),
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Código internalizable (ej. UPN-comp-01)', max_length=50)),
                ('description', models.TextField(help_text='Objetivo de aprendizaje medible')),
                ('bloom_level', models.CharField(blank=True, help_text='Nivel taxonomía Bloom', max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='courses.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='courses.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='courses.module')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Objetivo de aprendizaje',
                'verbose_name_plural': 'Objetivos de aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='LessonOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Resultado de aprendizaje esperado')),
                ('criteria', models.TextField(blank=True, help_text='Criterio de evaluación')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.lesson')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Resultado de lección',
                'verbose_name_plural': 'Resultados de lección',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=300)),
                ('from_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_from', to='courses.lesson')),
                ('to_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites_to', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'unique_together': {('from_lesson', 'to_lesson')},
            },
        ),
    ]
