# Generated by Django 5.1.7 on 2026-07-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_project_to_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='project',
        ),
    ]
