# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRawData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Nombre Campaña')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('loaded', 'Cargada'), ('completed', 'Completada')], default='pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='campaigns/raw_data/')),
                ('records_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiscadorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('loading', 'Cargando'), ('loaded', 'Cargado'), ('in_progress', 'En Progreso'), ('completed', 'Completada')], default='pending', max_length=20)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_processed', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='campaigns/discador_exports/')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discador_load', to='campaigns.providerrawdata')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani', models.CharField(max_length=20, verbose_name='Número Teléfono')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento Identidad')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('current_product', models.CharField(max_length=100, verbose_name='Producto Actual')),
                ('offered_product', models.CharField(max_length=100, verbose_name='Producto Ofrecido')),
                ('contact_type', models.CharField(choices=[('mobile', 'Móvil'), ('landline', 'Fijo'), ('whatsapp', 'WhatsApp')], default='mobile', max_length=20)),
                ('segment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segmento')),
                ('propensity_score', models.IntegerField(default=0, verbose_name='Score Propensión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='campaigns.providerrawdata')),
            ],
            options={
                'indexes': [models.Index(fields=['ani'], name='campaigns_c_ani_1e7f37_idx'), models.Index(fields=['dni'], name='campaigns_c_dni_4f7865_idx'), models.Index(fields=['campaign'], name='campaigns_c_campaig_722c2c_idx')],
            },
        ),
    ]
