# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Primer día del mes al que corresponde la tasa', unique=True, verbose_name='Fecha de referencia')),
                ('rate', models.DecimalField(decimal_places=6, help_text='Tasa promedio PEN/USD — Compra interbancaria', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, help_text='Primer día de la semana a la que corresponde el registro', verbose_name='Fecha')),
                ('semana', models.IntegerField(db_index=True, help_text='Número de semana ISO (calculado de fecha)', verbose_name='Semana')),
                ('agente', models.CharField(db_index=True, max_length=100, verbose_name='Agente')),
                ('supervisor', models.CharField(db_index=True, max_length=100, verbose_name='Supervisor')),
                ('servicio', models.CharField(choices=[('Reclamos', 'Reclamos'), ('Consultas', 'Consultas'), ('Ventas', 'Ventas'), ('Soporte', 'Soporte'), ('Cobranzas', 'Cobranzas')], db_index=True, max_length=50, verbose_name='Servicio')),
                ('canal', models.CharField(choices=[('Phone', 'Teléfono'), ('Mail', 'Email'), ('Chat', 'Chat'), ('WhatsApp', 'WhatsApp'), ('Social Media', 'Redes Sociales')], db_index=True, max_length=50, verbose_name='Canal')),
                ('eventos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eventos')),
                ('aht', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='AHT (segundos)')),
                ('evaluaciones', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Evaluaciones')),
                ('satisfaccion', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satisfacción (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Registro de llamadas',
                'verbose_name_plural': 'Registros de llamadas',
                'ordering': ['-fecha', 'agente'],
                'indexes': [models.Index(fields=['fecha', 'servicio'], name='kpis_cr_fecha_serv'), models.Index(fields=['fecha', 'canal'], name='kpis_cr_fecha_canal'), models.Index(fields=['fecha', 'agente'], name='kpis_cr_fecha_agente'), models.Index(fields=['fecha', 'supervisor'], name='kpis_cr_fecha_sup'), models.Index(fields=['semana', 'servicio'], name='kpis_cr_sem_serv')],
            },
        ),
    ]
