# Generated by Django 5.1.7 on 2026-08-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='resolved_on_first_call',
            field=models.BooleanField(default=False, verbose_name='Resuelto en primera llamada'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='abandoned',
            field=models.BooleanField(default=False, verbose_name='Llamada abandonada'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='asa',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ASA (segundos)'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='hora',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Hora del evento'),
        ),
    ]
