# Generated by Django 5.1.7 on 2026-07-17 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_remove_callrecord_uuid_remove_exchangerate_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
