# Generated by Django 5.1.7 on 2026-07-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0007_bot2_acd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simagentprofile',
            name='bot_specialization',
            field=models.CharField(blank=True, help_text='Especialización de BotInstance compatible. Valores: gtd_processor | project_manager | task_executor | calendar_optimizer | communication_handler | general_assistant. Vacío = perfil de uso general.', max_length=50),
        ),
    ]
