# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='bitacora/attachments/')),
                ('tipo', models.CharField(choices=[('image', 'Imagen'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Documento')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adjunto de Bitácora',
                'verbose_name_plural': 'Adjuntos de Bitácora',
            },
        ),
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('personal', 'Personal'), ('viaje', 'Viaje'), ('trabajo', 'Trabajo'), ('meta', 'Meta'), ('idea', 'Idea'), ('recuerdo', 'Recuerdo'), ('diario', 'Diario'), ('reflexion', 'Reflexión')], default='personal', max_length=50)),
                ('mood', models.CharField(blank=True, choices=[('muy_bien', '😄 Muy bien'), ('bien', '🙂 Bien'), ('neutral', '😐 Neutral'), ('mal', '😕 Mal'), ('muy_mal', '😞 Muy mal')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('structured_content', models.JSONField(blank=True, default=list, help_text='Bloques de contenido estructurado insertados desde courses')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
