# Generated by Django 5.1.7 on 2026-07-17 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacora', '0001_initial'),
        ('events', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraentry',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.event'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.project'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='related_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='rooms.cell'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.task'),
        ),
        migrations.AddField(
            model_name='bitacoraentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.tag'),
        ),
        migrations.AddField(
            model_name='bitacoraattachment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bitacora.bitacoraentry'),
        ),
    ]
