# Generated by Django 5.1.7 on 2026-07-17 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0005_add_is_active_if_missing'),
        ('events', '0006_alter_event_event_category'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('muy_bien', '😄 Muy bien'), ('bien', '🙂 Bien'), ('neutral', '😐 Neutral'), ('mal', '😕 Mal'), ('muy_mal', '😞 Muy mal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.event'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.project'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='related_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to='events.task'),
        ),
        migrations.AlterField(
            model_name='bitacoraentry',
            name='structured_content',
            field=models.JSONField(blank=True, default=list, help_text='Bloques de contenido estructurado insertados desde courses'),
        ),
    ]
